// Generated by gencpp from file romipi_msgs/NameList.msg
// DO NOT EDIT!


#ifndef ROMIPI_MSGS_MESSAGE_NAMELIST_H
#define ROMIPI_MSGS_MESSAGE_NAMELIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace romipi_msgs
{
template <class ContainerAllocator>
struct NameList_
{
  typedef NameList_<ContainerAllocator> Type;

  NameList_()
    : names()  {
    }
  NameList_(const ContainerAllocator& _alloc)
    : names(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _names_type;
  _names_type names;





  typedef boost::shared_ptr< ::romipi_msgs::NameList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::romipi_msgs::NameList_<ContainerAllocator> const> ConstPtr;

}; // struct NameList_

typedef ::romipi_msgs::NameList_<std::allocator<void> > NameList;

typedef boost::shared_ptr< ::romipi_msgs::NameList > NameListPtr;
typedef boost::shared_ptr< ::romipi_msgs::NameList const> NameListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::romipi_msgs::NameList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::romipi_msgs::NameList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace romipi_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'romipi_msgs': ['/home/ubuntu/catkin_ws/src/romipi_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::romipi_msgs::NameList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::romipi_msgs::NameList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::romipi_msgs::NameList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::romipi_msgs::NameList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::romipi_msgs::NameList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::romipi_msgs::NameList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::romipi_msgs::NameList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc7ae3609524b18034e49294a4ce670e";
  }

  static const char* value(const ::romipi_msgs::NameList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc7ae3609524b180ULL;
  static const uint64_t static_value2 = 0x34e49294a4ce670eULL;
};

template<class ContainerAllocator>
struct DataType< ::romipi_msgs::NameList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "romipi_msgs/NameList";
  }

  static const char* value(const ::romipi_msgs::NameList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::romipi_msgs::NameList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# list of robot name strings\n\
string[] names\n\
\n\
";
  }

  static const char* value(const ::romipi_msgs::NameList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::romipi_msgs::NameList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.names);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NameList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::romipi_msgs::NameList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::romipi_msgs::NameList_<ContainerAllocator>& v)
  {
    s << indent << "names[]" << std::endl;
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      s << indent << "  names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.names[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROMIPI_MSGS_MESSAGE_NAMELIST_H
