// Generated by gencpp from file romipi_msgs/RomiPose.msg
// DO NOT EDIT!


#ifndef ROMIPI_MSGS_MESSAGE_ROMIPOSE_H
#define ROMIPI_MSGS_MESSAGE_ROMIPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace romipi_msgs
{
template <class ContainerAllocator>
struct RomiPose_
{
  typedef RomiPose_<ContainerAllocator> Type;

  RomiPose_()
    : observer_name()
    , target_name()
    , pose()  {
    }
  RomiPose_(const ContainerAllocator& _alloc)
    : observer_name(_alloc)
    , target_name(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _observer_name_type;
  _observer_name_type observer_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _target_name_type;
  _target_name_type target_name;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::romipi_msgs::RomiPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::romipi_msgs::RomiPose_<ContainerAllocator> const> ConstPtr;

}; // struct RomiPose_

typedef ::romipi_msgs::RomiPose_<std::allocator<void> > RomiPose;

typedef boost::shared_ptr< ::romipi_msgs::RomiPose > RomiPosePtr;
typedef boost::shared_ptr< ::romipi_msgs::RomiPose const> RomiPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::romipi_msgs::RomiPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::romipi_msgs::RomiPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace romipi_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'romipi_msgs': ['/home/ubuntu/catkin_ws/src/romipi_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::romipi_msgs::RomiPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::romipi_msgs::RomiPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::romipi_msgs::RomiPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::romipi_msgs::RomiPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::romipi_msgs::RomiPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::romipi_msgs::RomiPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::romipi_msgs::RomiPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d8b91b3b0ff7649c81277385280f189";
  }

  static const char* value(const ::romipi_msgs::RomiPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d8b91b3b0ff7649ULL;
  static const uint64_t static_value2 = 0xc81277385280f189ULL;
};

template<class ContainerAllocator>
struct DataType< ::romipi_msgs::RomiPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "romipi_msgs/RomiPose";
  }

  static const char* value(const ::romipi_msgs::RomiPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::romipi_msgs::RomiPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# observer saw target at pose relative to observer\n\
string observer_name\n\
string target_name\n\
geometry_msgs/PoseStamped pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::romipi_msgs::RomiPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::romipi_msgs::RomiPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.observer_name);
      stream.next(m.target_name);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RomiPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::romipi_msgs::RomiPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::romipi_msgs::RomiPose_<ContainerAllocator>& v)
  {
    s << indent << "observer_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.observer_name);
    s << indent << "target_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.target_name);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROMIPI_MSGS_MESSAGE_ROMIPOSE_H
